apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/nick/.minikube/ca.crt
    server: https://192.168.39.53:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: homework
    user: cd
  name: cd
current-context: cd
kind: Config
preferences: {}
users:
- name: cd
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJVVUZpb2hYVWNDdnE3bUJReDJvTl85WHRjV2x2dHNMWjZpMVpMd0tXRWMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzM2MTg2MjU1LCJpYXQiOjE3MzYwOTk4NTUsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZjA1OTJkNTAtNzM1MS00MmQ2LWE1ZmYtY2YzNDFmMGJjNjQxIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJob21ld29yayIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJjZCIsInVpZCI6IjU0YTE3NzU4LWNiZWMtNDM1NC1iYTg2LTg1MjI3OWU3NWE2ZiJ9fSwibmJmIjoxNzM2MDk5ODU1LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aG9tZXdvcms6Y2QifQ.EmvbRoqZ0pIyKLk5rHXBrz_vXe9GLNccMcKTdLYzfXLNeiC3pM8ld2UAahU_OODV5SjGNRp2TKYSut3G8LAUUjDYPnOLLbD_tlsXAr8pzUqKlni5Td-hwLkwTIz6OOBpnP4KmYsN33UNP0cNS9qlE5wxeeMNDXIFmeIyTS_yziSAOGIhFjvSGY0LLEm7UWQQahF3WiDVO0jKFXHhtvEZwaLcts6bujM1eWoSKvCbYA9A8kY4nTlRPG1MIiQr5FfSB-N_EnubaYCt_xx2j3OlX7SdtadPTEmHsPEF2LM7yCZ9Fz-d8Rx5xXcGsCMo7G4NSWqA_PGfRz2SqufUl2RtZA 
    #    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJVVUZpb2hYVWNDdnE3bUJReDJvTl85WHRjV2x2dHNMWjZpMVpMd0tXRWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJob21ld29yayIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjZC10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQ3YzVjMWFkLTEyMTYtNDJkMy1iMzlkLTJiZGJlNWJlNDZmOSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpob21ld29yazpjZCJ9.jGTEzRLJjSXCG5Z76fOQcHlhl4z73Lzzb2kSrGZdlZCNXVwnALY9ffqhq-IWTr4ff4vAoX7c3M8w2mM2E3i1e_6_UBgH7quHKNJqynZ3pFXplTa_WZQV1IlC2oAzlpYOGNyIffnPMTvjkC-XG5eO68imBBTaKtEZnNS3uTm6kIzZp5KO-mP0J1tonSJ0CzbmNTy1xQVTlgBJhInIPIu0P0rbcuyxWXj26HogFq7qOuM9QzGAldQlnnf9IFp17RYGW5ikDEOEm3cU88DkqYCq4S9H8xly1UatCgohj_QCIUtzbdOXJljna39um9n-cYRIWF8ZgILyFFeqpcBVbH1rYg
