---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mionitoring-role
  namespace: homework
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes", "deployments"]
    verbs: ["get", "list", "watch"]
