apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.metadata.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.secret.metadata.annotations.serviceAccountName }}
type: kubernetes.io/service-account-token

