apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} 
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.labels.app }}
spec:
  clusterIP: {{ .Values.service.spec.clusterIP }}
  selector:
    app: {{ .Values.service.spec.selector.app }}
  ports:
    - protocol: {{ .Values.deployment.spec.template.spec.containers.ports.protocol }}
      port: {{ .Values.service.spec.ports.port }}
      targetPort: {{ .Values.deployment.spec.template.spec.containers.ports.name }}
  type: {{ .Values.service.type }}
