---
apiVersion: v1
kind: ServiceAccount
metadata:
#  annotations:
#    kubernetes.io/enforce-mountable-secrets: "true"
  name: {{ .Values.serviceAccountMon.metadata.name}}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
#  annotations:
#    kubernetes.io/enforce-mountable-secrets: "true"
  name: {{ .Values.serviceAccountAdm.metadata.name}}
  namespace: {{ .Release.Namespace }}
