apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: homework
spec:
  #  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
#  volumeName: homework-volume
  accessModes:
    - ReadWriteOnce
#  volumeMode: Filesystem
  resources: 
    requests:
      storage: 1Gi
  storageClassName: homework-stgclass #standard
#  selector:
#    matchLabels:
#      app: nginx
